add create password command

diff --git a/1p b/1p
--- a/1p
+++ b/1p
@@ -12,17 +12,25 @@ function signin {
 	eval $(op signin "${ACCOUNT:1:-1}")
 }
 
-function usage {
+function getUsage {
 	echo "
 1p Subcommands:
 
-    password    Get password for given account
-	"
+    password    Get password for given account"
 }
+
+function createUsage {
+	echo "
+1p Subcommands:
+
+    password    Create a random 32 bit password"
+}
+
 
 # Check requirements
 command -v op &> /dev/null || error "required program 'op' is not installed"
 command -v jq &> /dev/null || error "required program 'jq' is not installed"
+command -v openssl &> /dev/null || error "required program 'openssl' is not installed"
 
 # Check if no args
 if [ "$#" -eq 0 ]; then
@@ -36,7 +44,9 @@ do
     if [[ "$arg" =~ ^(-h|--help)$ ]]; then
 	    op "$@"
 		if [[ "$1" == "get" ]]; then
-			usage
+			getUsage
+		elif [[ "$1" == "create" ]]; then
+			createUsage
 		fi
 	    exit 0
     elif [[ "$arg" =~ ^(encode|update|signin|signout)$ ]]; then
@@ -48,12 +58,17 @@ done
 # Check if custom 1p command
 if [[ "$1" == "get" && "$2" == "password" ]]; then
 	if [ -z "$3" ]; then
-		error "account name not specified, try: 1p get password [<account>]"
+		error "account name not specified, try: 1p get password <account>"
 	fi
 	signin
 	ITEM=$(op get item $3)
 	[ $? -eq 0 ] || exit $?
 	echo "$ITEM" | jq '.details.fields[] | select(.designation=="password").value' --raw-output
+	exit 0
+elif [[ "$1" == "create" && "$2" == "password" ]]; then
+	PASSWORD=$(openssl rand -base64 32)
+	[ $? -eq 0 ] || error "error generating password, try: 1p create password"
+	echo "${PASSWORD}"
 	exit 0
 fi
 
